server:
  port: 9999
  servlet:
    context-path: /oAuth2 

# H2
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  security:
    filter:
      order: 3

logging:
  level:
    root: info